### ISSUE TITLE
Consider using new inspec GCP resources in test

### ISSUE THREAD

**Issue by brandoconnor** [newcontext-oss/terraform-google-instance#5]
Hey @nictrix 👋 

This work around GCP is excellent and something I'm particularly interested in seeing pushed forward. With how recently this was published in relation to the [new GCP inspec resources](https://github.com/inspec/inspec-gcp/tree/master/libraries), I wonder if there was a reason why the test suite opts to shell out to gcloud commands rather than use those resources. Obviously, the list of resources is far from exhaustive at this point but for simple example cases like you have here, that library seems suitable.

Was what you put forward here just the most expedient route to get started (perfectly valid start!) or is there an underlying technical constraint that's less obvious to me?

Thanks again on this project and your efforts in GCPlandia! 🙇

**Comment by nictrix** [comment]
Hey @brandoconnor 

I knew about inspec-gcp, but whoa there have been a ton of updates since I last looked. I didn't use it at the time because of missing functionality, but clearly, it's now there and I should be using it from now on. This is great news! Thanks for the heads up!

And thanks for the kind words, I'm trying to eat up a credit of $300 for signing up for GCP, but the tests are so fast and infrastructure so cheap I've barely scratched the surface. I do have plans on maturing this module through more screencasts/tutorials because it's on the Terraform registry.

**Comment by brandoconnor** [comment]
Excellent news and glad I could call the resources to your attention. Looking forward to the updates here.

**Comment by brandoconnor** [comment]
I'm super close to getting this working but blocked as I'm unable to force KT to invoke inspec with a necessary `--target gcp://` flag. I dropped a line on gitter. Hopefully, @ncs-alane can set me straight and help put that final piece in place. Issue is here: https://github.com/inspec/inspec-gcp/issues/37

If you can help get that issue resolved on the NC end, I'd be happy to create a branch here demonstrating how it all fits together. I don't know that anyone has stitched this toolchain together yet so a working example in the public sphere is **desperately** needed.

**Comment by nictrix** [comment]
@brandoconnor now that [KT v4.0.0](https://rubygems.org/gems/kitchen-terraform/versions/4.0.0) is released we can start getting inspec-gcp involved with the tests instead of the command line. Were you close to having it down already, shall I wait for a PR?

**Comment by brandoconnor** [comment]
I actually got this working just over the weekend. I really like how it's looking! I'll look to fork and PR within the week.

**Comment by KevinBuchs** [comment]
Problems are resolved with v0.2.0 release, https://github.com/newcontext-oss/terraform-google-instance/releases/tag/v0.2.0
